package:
  name: tifffile
  version: 2014.08.24

requirements:
  build:
    - python
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - tifffile

about:
  license: BSD
  home: http://www.lfd.uci.edu/~gohlke/
  summary: 'Read and write image data from and to TIFF files'
  